apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum-api-deployment
  labels:
    app: sum-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sum-api
  template:
    metadata:
      labels:
        app: sum-api
    spec:
      containers:
        - name: sum-api
          image: i4nv/micro-calculator-service:sum-api
          ports:
            - containerPort: 5001
          env:
            - name: APP_PORT
              value: "5001"
